Fix aggregate report
DBCG/cql-evaluator pull request #69
Opened 2021-11-03 21:19 UTC by mdnazmulkarim

validate test script for subject-list reports

2021-11-04 21:17 UTC, bryantaustin13 approved these changes
LGTM. Builds clean and tests pass.

2021-11-30 17:46 UTC, JPercival requested changes

2021-11-30 17:46 UTC, JPercival commented on evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureReportAggregator.java
> +                if (resourceMap.containsKey(resource.getId())) {
The lists here may have different Ids. You'll have to pick the correct list based on the population list reference in the population group.

2022-02-02 22:29 UTC, JPercival approved these changes
Needs some tweaks on subject-list merging, but I'll work on that.

2022-02-02 22:44 UTC, merged