R4MeasureBuilder population count fix based on extension
DBCG/cql-evaluator pull request #85
Opened 2022-03-08 23:34 UTC by mdnazmulkarim

Utilizing extension(http://build.fhir.org/ig/HL7/cqf-measures/StructureDefinition-cqfm-populationBasis.html) 
to determine type of measure for measure evaluation.
Based on type the population count can be boolean or concrete value

2022-03-09 04:02 UTC, brynrhodes approved these changes

2022-03-09 16:52 UTC, JPercival commented
Can add this to dstu3 as well to make sure the codebases stay in sync?

2022-03-10 00:06 UTC, JPercival requested changes

2022-03-10 00:06 UTC, JPercival commented on evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureDefBuilder.java
> +            if (StringUtils.isNotBlank(group.getId())) {
There's no need for a null check here. You can just set the id.

2022-03-10 00:06 UTC, JPercival commented on evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/dstu3/Dstu3MeasureDefBuilder.java
> +            if (StringUtils.isNotBlank(group.getId())) {
No need for a null check here.

2022-03-10 00:06 UTC, JPercival commented on evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureReportBuilder.java
> +                    CollectionUtils.isEmpty(populationDef.getResources()) ?
Why not use getResources.size() ? what is the isEmpty check add?

2022-03-10 00:06 UTC, JPercival commented on evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureEvaluation.java
> +                if ((groupDef.get(INITIALPOPULATION) != null ? groupDef.get(INITIALPOPULATION).getResources().size() : 0) <
If groupDef.get() returns null, it was likely initialized incorrectly. It's not clear why you need all the null checks here.

2022-03-10 00:06 UTC, JPercival commented on evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/GroupDef.java
> +    private String id = "";
This should default to null rather than being blank.

2022-05-04 16:13 UTC, JPercival approved these changes

2022-05-10 17:07 UTC, merged