Fix Unresolved ValueSet Expansion
DBCG/cql-evaluator pull request #93
Opened 2022-04-20 00:07 UTC by jreyno77

Added check for unexpanded valuesets with expansion logic and throw error

Added tests for change

2022-04-20 19:59 UTC, JPercival requested changes

2022-04-20 19:59 UTC, JPercival commented on evaluator.fhir/src/test/resources/org/opencds/cqf/cql/evaluator/engine/util/r4/TestBundleValueSetsTwo.json
> +    "id": "test-bundle-two-valuesets",
Let's give this an id / filename that indicates that this content is actually for testing logic expansion.

2022-04-20 20:35 UTC, Jinip submitted a review, later dismissed
Add a check for an expansion parameter named "naive" with a value "true", which are value sets expanded by the EnsureExecutableValueSet tooling function, not a terminology server. Return an info level error message that says something to the effect of "codes expanded without a terminology server, some results may not be correct"

2022-04-29 18:34 UTC, JPercival approved these changes

2022-04-29 18:35 UTC, merged